rabbitmq:
  host: 'cow.rmq2.cloudamqp.com'
  port: 5672
  user: 'cablqldr'
  password: '77enssqw-7f3OrFdhyXPqcbINR-tXYfj'
  vhost: 'cablqldr'
  exchange: 'ksiazki'
  readers_exchange: 'czytelnicy'

database:
  url: "/data/wypozyczenia.db"

service:
  port: 8082
  debug: False
