rabbitmq:
  host: 'cow.rmq2.cloudamqp.com'
  port: 5672
  user: 'cablqldr'
  password: '77enssqw-7f3OrFdhyXPqcbINR-tXYfj'
  vhost: 'cablqldr'
  exchange: 'ksiazki'

database:
  url: "sqlite:///data/katalog.db"

service:
  port: 8080
